---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-demo-sumeng-com-v1-order
  failurePolicy: Fail
  name: vorder.kb.io
  rules:
  - apiGroups:
    - demo.sumeng.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - orders
  sideEffects: None
