# permissions for end users to view orders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: order-viewer-role
rules:
- apiGroups:
  - demo.sumeng.com
  resources:
  - orders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.sumeng.com
  resources:
  - orders/status
  verbs:
  - get
